#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import datetime
from gradelib import *

r = Runner(save("jos.out"),
           stop_breakpoint("cons_getc"))

@test(50)
def test_date():
    r.user_test("date", timeout=30)
    r.match(datetime.datetime.utcnow().strftime("DATE: %Y-%m-%d %H:\d\d:\d\d"))

@test(50)
def test_vdate():
    r.user_test("vdate", timeout=30)
    r.match(datetime.datetime.utcnow().strftime("VDATE: %Y-%m-%d %H:\d\d:\d\d"))

run_tests()
