#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from gradelib import *

r = Runner(save("jos.out"),
           stop_breakpoint("readline"))

@test(0, "running JOS")
def test_jos():
    r.run_qemu()

@test(100, "Physical page allocator", parent=test_jos)
def test_check_page_alloc():
    r.match(r"Memory allocator is initialized",
            r"Physical memory tree is correct")

run_tests()
